In [1]:
import numpy as np

In [2]:
# "argument" from astronomy
# tables where light reflects
# "that which eluminates something else"

In [3]:
data = np.loadtxt('Lending-company-Numeric.csv',delimiter=',')
print(data)

[[ 2000.    40.   365.  3121.  4241. 13621.]
 [ 2000.    40.   365.  3061.  4171. 15041.]
 [ 1000.    40.   365.  2160.  3280. 15340.]
 ...
 [ 2000.    40.   365.  4201.  5001. 16600.]
 [ 1000.    40.   365.  2080.  3320. 15600.]
 [ 2000.    40.   365.  4601.  4601. 16600.]]


In [6]:
# argwhere
# conditionals
# check whether element satisfies given condition

# default is "!= 0"
# find nonzeroes
print(np.argwhere(data))

# find zeroes
print(np.argwhere(data == False))

[[   0    0]
 [   0    1]
 [   0    2]
 ...
 [1042    3]
 [1042    4]
 [1042    5]]
[[116   4]
 [430   3]]


In [9]:
# is even
print(np.argwhere(data %2 == 0))

[[   0    0]
 [   0    1]
 [   1    0]
 ...
 [1042    0]
 [1042    1]
 [1042    5]]


In [10]:
# conditional slicing = filtering for actual values
# argwhere = returns indicies

In [11]:
# no method

In [13]:
data_nan = np.genfromtxt('Lending-company-Numeric-NAN.csv', delimiter=';')
print(data_nan)

[[ 2000.    40.   365.  3121.  4241. 13621.]
 [ 2000.    40.   365.  3061.  4171. 15041.]
 [ 1000.    40.   365.  2160.  3280. 15340.]
 ...
 [   nan    40.   365.  4201.  5001. 16600.]
 [ 1000.    40.   365.  2080.  3320. 15600.]
 [ 2000.    40.   365.  4601.  4601. 16600.]]


In [28]:
print(np.isnan(data_nan))

# before - missing values
print(data_nan[175])
# use argwhere to see indicies for missing values
np.argwhere(np.isnan(data_nan))
# use a for loop to save zero over them
for idx in np.argwhere(np.isnan(data_nan)):
    data_nan[idx[0], idx[1]] = 0
# after - zeroes
print(data_nan[175])
# check for nans
print('there are ', np.isnan(data_nan).sum(), 'missing values')

[[False False False False False False]
 [False False False False False False]
 [False False False False False False]
 ...
 [False False False False False False]
 [False False False False False False]
 [False False False False False False]]
[ 2000.     0.     0.  1851.  3051. 13561.]
[ 2000.     0.     0.  1851.  3051. 13561.]
there are  0 missing values
