In [1]:
import numpy as np

In [2]:
data = np.loadtxt('Lending-company-Numeric.csv', delimiter=',')
print(data)

In [4]:
# concatenate = along a given axis
print(np.concatenate((data[0,:], data[1,:])))

[ 2000.    40.   365.  3121.  4241. 13621.  2000.    40.   365.  3061.
  4171. 15041.]


In [7]:
data_nan = np.genfromtxt('Lending-company-Numeric-NAN.csv', delimiter=';')
# one larger than the max in the dataset
max_fill = np.nanmax(data_nan).round(2) + 1
mean_fill = np.nanmean(data_nan, axis=0).round(2)
data_nan = np.genfromtxt('Lending-company-Numeric-NAN.csv',
                        delimiter=';',
                        filling_values=max_fill)
# switch for mean in every column
for i in range(data_nan.shape[1]):
    data_nan[:,i] = np.where(data_nan[:,i] == max_fill, mean_fill[i], data_nan[:,i])
print(data_nan)

[[ 2000.      40.     365.    3121.    4241.   13621.  ]
 [ 2000.      40.     365.    3061.    4171.   15041.  ]
 [ 1000.      40.     365.    2160.    3280.   15340.  ]
 ...
 [ 2250.25    40.     365.    4201.    5001.   16600.  ]
 [ 1000.      40.     365.    2080.    3320.   15600.  ]
 [ 2000.      40.     365.    4601.    4601.   16600.  ]]


In [11]:
# column upon column
print(np.concatenate((data,data_nan)))
print(np.concatenate((data,data_nan)).shape)

print('----------')

# row upon row
print(np.concatenate((data,data_nan), axis=1))
print(np.concatenate((data,data_nan), axis=1).shape)

[[ 2000.      40.     365.    3121.    4241.   13621.  ]
 [ 2000.      40.     365.    3061.    4171.   15041.  ]
 [ 1000.      40.     365.    2160.    3280.   15340.  ]
 ...
 [ 2250.25    40.     365.    4201.    5001.   16600.  ]
 [ 1000.      40.     365.    2080.    3320.   15600.  ]
 [ 2000.      40.     365.    4601.    4601.   16600.  ]]
(2086, 6)
----------
[[ 2000.    40.   365. ...  3121.  4241. 13621.]
 [ 2000.    40.   365. ...  3061.  4171. 15041.]
 [ 1000.    40.   365. ...  2160.  3280. 15340.]
 ...
 [ 2000.    40.   365. ...  4201.  5001. 16600.]
 [ 1000.    40.   365. ...  2080.  3320. 15600.]
 [ 2000.    40.   365. ...  4601.  4601. 16600.]]
(1043, 12)


In [ ]:
# works just like cstack, dstack, hstack
# but, only the axis we are moving along has to match