In [1]:
import numpy as np

In [5]:
file = np.loadtxt('Lending-company-Numeric.csv', delimiter=',')
print(file)

[[ 2000.    40.   365.  3121.  4241. 13621.]
 [ 2000.    40.   365.  3061.  4171. 15041.]
 [ 1000.    40.   365.  2160.  3280. 15340.]
 ...
 [ 2000.    40.   365.  4201.  5001. 16600.]
 [ 1000.    40.   365.  2080.  3320. 15600.]
 [ 2000.    40.   365.  4601.  4601. 16600.]]


In [15]:
# check for null values
# use the sum to check all values. If false, sum will be not zero
print('there are', np.isnan(file).sum(), 'missing values')

there are 0 missing values


In [23]:
# with nans, loactxt crashes
# file2 = np.loadtxt('Lending-company-Numeric-NAN.csv', delimiter=';')
file2 = np.genfromtxt('Lending-company-Numeric-NAN.csv', delimiter=';')
print(file2)

# check for missing values
print('there are', np.isnan(file2).sum(), 'missing values')

# fill values
# not always a good idea to replace with zero
file2 = np.genfromtxt('Lending-company-Numeric-NAN.csv',
                      delimiter=';',
                     filling_values=0)

# instead, fill with a value higher than all in the data set >> filter out
max_fill = np.nanmax(file2).round(2) + 1
print('fill with', fill)
file2 = np.genfromtxt('Lending-company-Numeric-NAN.csv',
                      delimiter=';',
                     filling_values=max_fill)
print('there are', np.isnan(file2).sum(), 'missing values')

[[ 2000.    40.   365.  3121.  4241. 13621.]
 [ 2000.    40.   365.  3061.  4171. 15041.]
 [ 1000.    40.   365.  2160.  3280. 15340.]
 ...
 [   nan    40.   365.  4201.  5001. 16600.]
 [ 1000.    40.   365.  2080.  3320. 15600.]
 [ 2000.    40.   365.  4601.  4601. 16600.]]
there are 260 missing values
fill with 64002.0
there are 0 missing values


In [34]:
# other ways
# fill with mean
mean_fill = np.nanmean(file2, axis=0).round(2)
print(mean_fill)

# with max fill, we have trouble with our means
# could cause misleading insights
print('mean col 0 with max_fill', np.mean(file2[:,0]).round(2))
# in col 0, replace max_fill with mean_fill for col 0, leaving non-filler unchanged
file2[:,0] = np.where(file2[:,0] == max_fill,
                     mean_fill[0],
                     file2[:,0])
# check if it equals the mean
def check_mean():
    if np.mean(file2[:,0]).round(2) == mean_fill[0]:
        print('they are equal now')
check_mean()
    
# loop to do it to all of them
for i in range(file2.shape[1]):
    file2[:,i] = np.where(file2[:,i] == max_fill,
                          mean_fill[0],
                          file2[:,0])
check_mean()

[ 2315.87  2989.43  3537.7   7468.93  7304.54 17753.79]
mean col 0 with max_fill 2315.87
they are equal now
they are equal now


In [ ]:
# can also use np.where to remove other values (e.g. negatives with < 0)