In [1]:
import numpy as np

In [2]:
file = np.loadtxt('Lending-company-Numeric.csv', delimiter=',')
print(file)

[[ 2000.    40.   365.  3121.  4241. 13621.]
 [ 2000.    40.   365.  3061.  4171. 15041.]
 [ 1000.    40.   365.  2160.  3280. 15340.]
 ...
 [ 2000.    40.   365.  4201.  5001. 16600.]
 [ 1000.    40.   365.  2080.  3320. 15600.]
 [ 2000.    40.   365.  4601.  4601. 16600.]]


In [6]:
# delete a single value
print(file.size)
print(np.delete(file, 0).size)

6258
6257


In [9]:
# delete a col
print(np.delete(file,0,axis=0))
# delete row
print(np.delete(file,0,axis=1))

# multiple cols
print(np.delete(file,[0,2,4],axis=0))
# print(np.delete(file,(0,2,4),axis=0))

# multiple rows
print(np.delete(file,[0,2,4],axis=1))

print('----------')
# rows and columns
# delete rows first, then cols on same line
print(np.delete(np.delete(file,[0,2,4],axis=1),[0,2,4],axis=0))

[[ 2000.    40.   365.  3061.  4171. 15041.]
 [ 1000.    40.   365.  2160.  3280. 15340.]
 [ 2000.    40.   365.  3041.  4241. 15321.]
 ...
 [ 2000.    40.   365.  4201.  5001. 16600.]
 [ 1000.    40.   365.  2080.  3320. 15600.]
 [ 2000.    40.   365.  4601.  4601. 16600.]]
[[   40.   365.  3121.  4241. 13621.]
 [   40.   365.  3061.  4171. 15041.]
 [   40.   365.  2160.  3280. 15340.]
 ...
 [   40.   365.  4201.  5001. 16600.]
 [   40.   365.  2080.  3320. 15600.]
 [   40.   365.  4601.  4601. 16600.]]
[[ 2000.    40.   365.  3061.  4171. 15041.]
 [ 2000.    40.   365.  3041.  4241. 15321.]
 [ 2000.    40.   365.  3201.  4141. 14141.]
 ...
 [ 2000.    40.   365.  4201.  5001. 16600.]
 [ 1000.    40.   365.  2080.  3320. 15600.]
 [ 2000.    40.   365.  4601.  4601. 16600.]]
[[   40.  3121. 13621.]
 [   40.  3061. 15041.]
 [   40.  2160. 15340.]
 ...
 [   40.  4201. 16600.]
 [   40.  2080. 15600.]
 [   40.  4601. 16600.]]
----------
[[   40.  3061. 15041.]
 [   40.  3041. 15321.]
 [   