In [11]:
import numpy as np
from numpy.random import shuffle

In [12]:
# rearrange order wihtout changing rows
# random sample is representative of the dataset

In [13]:
data = np.loadtxt('Lending-company-Numeric.csv', delimiter=',')[:8]
print(data)

[[ 2000.    40.   365.  3121.  4241. 13621.]
 [ 2000.    40.   365.  3061.  4171. 15041.]
 [ 1000.    40.   365.  2160.  3280. 15340.]
 [ 2000.    40.   365.  3041.  4241. 15321.]
 [ 2000.    50.   365.  3470.  4820. 13720.]
 [ 2000.    40.   365.  3201.  4141. 14141.]
 [ 2000.    50.   365.  1851.  3251. 17701.]
 [ 2000.    40.   365.  3971.  4131. 15351.]]


In [14]:
shuffle(data)
print(data)
print('----------')
shuffle(data)
print(data)
print('----------')
shuffle(data)
print(data)

[[ 2000.    40.   365.  3041.  4241. 15321.]
 [ 2000.    50.   365.  3470.  4820. 13720.]
 [ 2000.    40.   365.  3971.  4131. 15351.]
 [ 2000.    40.   365.  3121.  4241. 13621.]
 [ 2000.    50.   365.  1851.  3251. 17701.]
 [ 1000.    40.   365.  2160.  3280. 15340.]
 [ 2000.    40.   365.  3201.  4141. 14141.]
 [ 2000.    40.   365.  3061.  4171. 15041.]]
----------
[[ 2000.    40.   365.  3061.  4171. 15041.]
 [ 2000.    50.   365.  3470.  4820. 13720.]
 [ 2000.    40.   365.  3971.  4131. 15351.]
 [ 2000.    50.   365.  1851.  3251. 17701.]
 [ 2000.    40.   365.  3041.  4241. 15321.]
 [ 1000.    40.   365.  2160.  3280. 15340.]
 [ 2000.    40.   365.  3201.  4141. 14141.]
 [ 2000.    40.   365.  3121.  4241. 13621.]]
----------
[[ 1000.    40.   365.  2160.  3280. 15340.]
 [ 2000.    40.   365.  3201.  4141. 14141.]
 [ 2000.    40.   365.  3971.  4131. 15351.]
 [ 2000.    40.   365.  3061.  4171. 15041.]
 [ 2000.    40.   365.  3121.  4241. 13621.]
 [ 2000.    50.   365.  1851.  

In [ ]:
# use the method on random generators
from numpy.random import Generator as gen
from numpy.random import PCG64 as pcg
a = gen(pcg())
a.shuffle(data)
print(data)
# it prevails over the use of seeds
# can't replicate a shuffle with seeds