In [1]:
import numpy as np

In [24]:
data = np.genfromtxt(r'C:\Users\nbrock\OneDrive\coding\jupyter-notebooks\data-analyst-course\working-with-files\files\Lending-Company-Total-Price.csv',
                 delimiter=',',
                 dtype='str',
                 skip_header=1,
                 usecols=[1,2,4])
print(data)

[['id_1' 'Product B' 'Location 2']
 ['id_2' 'Product B' 'Location 3']
 ['id_3' 'Product C' 'Location 5']
 ...
 ['id_413' 'Product B' 'Location 135']
 ['id_414' 'Product C' 'Location 200']
 ['id_415' 'Product A' 'Location 8']]


In [25]:
data[:,0] = np.chararray.strip(data[:,0], 'id_')
data[:,1] = np.chararray.strip(data[:,1], 'Product ')
data[:,2] = np.chararray.strip(data[:,2], 'Location ')
print(data)

[['1' 'B' '2']
 ['2' 'B' '3']
 ['3' 'C' '5']
 ...
 ['413' 'B' '135']
 ['414' 'C' '200']
 ['415' 'A' '8']]


In [26]:
# replace letters with numbers
product_letters = ['A', 'B', 'C', 'D', 'E', 'F']
for l in range(len(product_letters)):
    data[:,1] = np.where(data[:,1] == product_letters[l], l+1, data[:,1])
print(data)

[['1' '2' '2']
 ['2' '2' '3']
 ['3' '3' '5']
 ...
 ['413' '2' '135']
 ['414' '3' '200']
 ['415' '1' '8']]


In [27]:
# dtypes
data = data.astype('int32')
print(data)

[[  1   2   2]
 [  2   2   3]
 [  3   3   5]
 ...
 [413   2 135]
 [414   3 200]
 [415   1   8]]


In [ ]:
# all clean!