In [1]:
import numpy as np

In [2]:
data = np.loadtxt('Lending-company-Numeric.csv', delimiter=',')
print(data)

[[ 2000.    40.   365.  3121.  4241. 13621.]
 [ 2000.    40.   365.  3061.  4171. 15041.]
 [ 1000.    40.   365.  2160.  3280. 15340.]
 ...
 [ 2000.    40.   365.  4201.  5001. 16600.]
 [ 1000.    40.   365.  2080.  3320. 15600.]
 [ 2000.    40.   365.  4601.  4601. 16600.]]


In [3]:
# numeric are sorted in ascending order
# strings are organized by ASCII
print(np.unique(data))

[-2870. -2550. -2450. ... 52751. 54625. 64001.]


In [12]:
unique_values = np.unique(data[:,1], return_index=True, return_counts=True)
print(unique_values)
for n in range(len(unique_values[0])):
    print(int(unique_values[0][n]), 'appears', unique_values[2][n], 'times in the dataset, first at position', unique_values[1][n])

(array([ 35.,  40.,  50., 125., 165.]), array([327,   0,   4,  19,  27], dtype=int64), array([  4, 567, 451,  19,   2], dtype=int64))
35 appears 4 times in the dataset, first at position 327
40 appears 567 times in the dataset, first at position 0
50 appears 451 times in the dataset, first at position 4
125 appears 19 times in the dataset, first at position 19
165 appears 2 times in the dataset, first at position 27
