In [3]:
import numpy as np

In [7]:
# matricies
# conditon: must have same dimensions
m1 = np.array([[5,12,6], [-3,0,14]])
m2 = np.array([[6,2,-4], [7,0,5]])

print(m1 + m2)
print('--------------------')
print(m1 - m2)

[[11 14  2]
 [ 4  0 19]]
--------------------
[[ -1  10  10]
 [-10   0   9]]


In [8]:
# vectors
# same lengths
v1 = np.array([1,2,3,4,5])
v2 = np.array([5,4,3,2,1])
v1 + v2

array([6, 6, 6, 6, 6])

In [9]:
# scalars
5+5

10

In [11]:
# can add scalars to matricies / vectors.
# adds the scalar to each element
print(v1 + 10)
print('--------------------')
print(m1 + 10)

[11 12 13 14 15]
--------------------
[[15 22 16]
 [ 7 10 24]]
