In [1]:
import numpy as np

In [8]:
# scalar
s = 5
# vector
v = np.array([5, -2, 4])
# matrix
m = np.array([[5,12,6], [-3,0,14]])

print(s)
print(v)
print(m)

5
[ 5 -2  4]
[[ 5 12  6]
 [-3  0 14]]


data types

In [10]:
print(type(s))
print(type(v))
print(type(m))
# ndarray = n-demensional array

<class 'int'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [12]:
# declar scalar as array
s_array = np.array(s)
print(type(s_array))

<class 'numpy.ndarray'>


data shapes

In [15]:
# check dimensionality
# error
# print(s.shape)
# no dimensions
print(s_array.shape)

()
(3,)
(2, 3)


In [19]:
# 3 ordered elements
print(v.shape)
# reshape from row to column
print(v.reshape(1,3))
print(v.reshape(3,1))

(3,)
[[ 5 -2  4]]
[[ 5]
 [-2]
 [ 4]]
