In [12]:
import numpy as np
from random import randint

In [4]:
# dot product / scalar product
# sum of the products of the corresponding elements
# result is a scalar
# vectors
v1 = np.array([5,10,15])
v2 = np.array([2,3,4])
# dot product
print(np.dot(v1,v2))

[10 30 60]
100


In [5]:
# scalar * vector
v1 * 5
# ie initial vector "scaled 5 times"

array([25, 50, 75])

In [11]:
# matricies
# first dimension must match second dimension of the other
# (3 x 4) can be multiplied by (1 x 3), (2 x 3), (3 x 3),... opposing shape
# repeating dimension (in this case 3) will dissappear in the resulting matrix ege (2 x 3) * (3 x 6) = (2 x 6)
# use distributive property; first vector times first vector, first vector times second vector...

# error
# (3 x 2) * (3 x 2)
# m1 = np.array([[10,-5,3], [14,21,9]])
# m2 = np.array([[5,12,-6], [5,20,-5]])
# better!
# (3 x 2) * (2 x 3)
m1 = np.array([[10,-5,3], [14,21,9]])
m2 = np.array([[5,12], [5,20], [-6, -5]])

print(np.dot(m1,m2))

[[  7   5]
 [121 543]]


In [ ]:
matching_side = 10
side_a = 5
side_b = 20

def create_dot_matricies():
    m1_list = []
    m2_list = []
    for n in range(0,10):
        for i in range(0,side_a):
            v = []