In [1]:
# import !=  load
# import doesn't track the original datatypes

In [2]:
# pandas
import pandas as pd
df = pd.read_csv('./files/sample.csv')
df.to_csv('./files/pd_copy.csv', index=False)

In [3]:
import numpy as np
data = np.genfromtxt('./files/sample_numeric.csv',
                    delimiter=',',
                    skip_header=1)
print(data)

[[4436. 2925.]
 [4031. 3431.]
 [2071. 6789.]
 [3947. 5858.]
 [2623. 7490.]
 [ 314. 7882.]
 [3918. 4334.]
 [1191. 6123.]
 [1841. 6786.]]


In [4]:
# npsave()
# numpy creates a .npy file
# 20x faser than csv
# less memory space
# load rather than import

import numpy as np
np.save('./files/numpy-save', data)

In [5]:
loaded = np.load('./files/numpy-save.npy')
print(loaded)

[[4436. 2925.]
 [4031. 3431.]
 [2071. 6789.]
 [3947. 5858.]
 [2623. 7490.]
 [ 314. 7882.]
 [3918. 4334.]
 [1191. 6123.]
 [1841. 6786.]]


In [6]:
# same data!
np.array_equal(data, loaded)

True

In [7]:
# np savez()
# creates a .npz = archive that can store multiple arrays
np.savez('./files/numpy-savez', data, loaded)

In [8]:
savez_data = np.load('./files/numpy-savez.npz')
# specify which array you want to open
print(savez_data['arr_0'])


[[4436. 2925.]
 [4031. 3431.]
 [2071. 6789.]
 [3947. 5858.]
 [2623. 7490.]
 [ 314. 7882.]
 [3918. 4334.]
 [1191. 6123.]
 [1841. 6786.]]


In [9]:
# you can name them

np.savez('./files/numpy-savez', orig_data=data, load_data=loaded)

savez_data = np.load('./files/numpy-savez.npz')
# specify which array you want to open
print(savez_data['load_data'])

[[4436. 2925.]
 [4031. 3431.]
 [2071. 6789.]
 [3947. 5858.]
 [2623. 7490.]
 [ 314. 7882.]
 [3918. 4334.]
 [1191. 6123.]
 [1841. 6786.]]


In [10]:
# np.savetxt()
# format as string
# delimiter is comma
np.savetxt('./files/numpy-savetxt.txt',
           data,
          fmt='%s',
          delimiter=',')

In [14]:
data_savetxt = np.genfromtxt('./files/numpy-savetxt.txt',
                    delimiter=',',
                    dtype=float)
print(data_savetxt)

[[4436. 2925.]
 [4031. 3431.]
 [2071. 6789.]
 [3947. 5858.]
 [2623. 7490.]
 [ 314. 7882.]
 [3918. 4334.]
 [1191. 6123.]
 [1841. 6786.]]


In [15]:
np.array_equal(data, data_savetxt)

True