In [1]:
import numpy as np

In [2]:
# assign from RAM memory
# could be blank, could be random values
a = np.empty(shape=(2,3))
print(a)

[[0. 0. 0.]
 [0. 0. 0.]]


In [3]:
# zeros
b = np.zeros(shape=(2,3), dtype='int8')
print(b)

[[0 0 0]
 [0 0 0]]


In [4]:
# ones
c = np.ones(shape=(2,3))
print(c)

[[1. 1. 1.]
 [1. 1. 1.]]


In [9]:
# specified value
d = np.full(fill_value=2, shape=(2,3))
print(d)
d_str = np.full(fill_value='two', shape=(2,3))
print(d_str)

[[2 2 2]
 [2 2 2]]
[['two' 'two' 'two']
 ['two' 'two' 'two']]


In [13]:
# like
# don't sepcify shape or type
# specify another array and let the new array be the same shape and type

from random import randint
m = np.array([[randint(0,10),randint(0,10),randint(0,10),randint(0,10),randint(0,10)],
             [randint(0,10),randint(0,10),randint(0,10),randint(0,10),randint(0,10)],
             [randint(0,10),randint(0,10),randint(0,10),randint(0,10),randint(0,10)]])
print(m)
print('------------------')

# replicate the given array with the empty function
m2 = np.empty_like(m)
print(m2)
print('------------------')

m3 = np.zeros_like(m2)
print(m3)

# np.ones_like
# np.full_like

[[3 9 9 1 9]
 [1 4 0 8 1]
 [8 3 5 5 7]]
------------------
[[      0       0       0       0       0]
 [      0       0       0       0       0]
 [   1596       0       0 6029409       0]]
------------------
[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


In [22]:
# arange = array range
# consec int values in a range

# like py "range"...
a2a = list(range(30))
print(a2a, end=' ')
print('\n', type(a2a), type(range(30)))
print('------------------')

# but produces array instead of range object
a2b = np.arange(30)
print(a2)
print(type(a2b))

# start, stop step

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29] 
 <class 'list'> <class 'range'>
------------------
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]
<class 'numpy.ndarray'>


In [23]:
# random bit generator
from numpy.random import Generator as gen
# "permiutation congruential generator" up to 64 bit size
from numpy.random import PCG64 as pcg

In [27]:
# define object
# empty argument randomly selects a "seed" = starting parameters for the algorithm
r = gen(pcg())
# normal distribution
print(r.normal(size=(2,3)))
print('--------------------')

# define the seed
# keep the same values for ONE execution
# if you want to use it many times, reset it every time
r = gen(pcg(365))
print(r.normal(size=(5,5)))

[[-1.53435776  0.09832967 -0.75687539]
 [-0.82479331  0.86500849 -0.5853009 ]]
--------------------
[[-0.13640899  0.09414431 -0.06300442  1.05391641 -0.6866818 ]
 [-0.50922173 -0.7999526   0.73041825  0.08825439 -2.1177576 ]
 [ 0.65526774 -0.48095012 -0.5519114  -0.58578662 -0.98257896]
 [ 1.12378166 -1.30984316 -0.04703774  0.955272    0.26071745]
 [-0.20023668 -1.50172484 -1.4929163   0.96535084  1.18694633]]


In [31]:
# normal
print(r.normal(20,size=(5,5)))
print('--------------------')
# integers
print(r.integers(20,size=(5,5)))
print('--------------------')
# random, continuous dist
print(r.random(size=(5,5)))
print('--------------------')
# discrete, uniform dist
# define the statistical likelihood of a number being selected with "p"
print(r.choice([1,2,3,4,5], p=[0.1,0.1,0.1,0.1,0.6], size=(5,5)))

[[19.12228651 18.87587889 19.5453674  19.09856506 19.13163972]
 [19.27222634 20.56618451 22.08803027 19.87628573 20.03820826]
 [18.61744239 20.81950753 19.72514882 18.96163647 19.83913036]
 [20.19711906 18.77856883 21.09267177 21.85390059 20.9733405 ]
 [19.85759534 19.57137593 21.15921193 20.27403717 20.05206376]]
--------------------
[[ 0  5  6 17 14]
 [13  2  9 19 18]
 [ 1 14  7 17  4]
 [ 1  1 15  8 17]
 [ 6 11 15  0  9]]
--------------------
[[0.61814204 0.61521597 0.48029186 0.17779049 0.33077715]
 [0.54756582 0.14648211 0.10508127 0.20793472 0.29252908]
 [0.13680607 0.13215934 0.29111928 0.65803493 0.39732069]
 [0.21643789 0.85769281 0.16366919 0.07551735 0.56534831]
 [0.00426888 0.54130757 0.2720943  0.78355963 0.76898416]]
--------------------
[[5 5 5 1 3]
 [5 5 3 5 5]
 [5 2 5 5 4]
 [5 5 5 5 5]
 [5 4 5 5 5]]


In [32]:
# probability dist

# poisson = over fixed interval of time, expect a value to occur exactly "lambda" times
r = gen(pcg(seed=365))
print(r.poisson(lam=10, size=(5,5)))
# 10 times is not realistic

[[11 12 12 14 13]
 [ 9 10 11 11  8]
 [11  8 10  9 14]
 [ 7  8  9 15 15]
 [13  8  8  7  9]]


In [33]:
# binomial
# only two outcomes
# n = num experiments
# p = probability of getting certain outcome
r = gen(pcg(seed=365))
print(r.binomial(n=100,p=.4,size=(5,5)))

[[42 44 30 36 45]
 [36 41 38 42 41]
 [35 31 35 46 29]
 [41 41 46 34 48]
 [45 45 45 40 43]]


In [34]:
# logistic
# location
# scale
r = gen(pcg(seed=365))
print(r.logistic(loc=9, scale=1.2,size=(5,5)))

[[10.37767822 10.42451863  9.63404367  7.36153427  9.82286787]
 [ 5.81223125 10.09354231  6.46790532 11.38740256  8.97147918]
 [10.85844698  8.79081317  5.962079    9.99560681  8.34539118]
 [ 7.97105522  8.9981544   8.93530194  9.6253307   9.23850869]
 [ 9.73729284  5.3090678  10.13723528 11.04372782  7.11078651]]


In [37]:
# applications
# "test creation" = when real data isn't available, need random data to test a program
r = gen(pcg(seed=365))

# set the size to the same so it all fits together
col1 = r.normal(loc=2,scale=3,size=1000)
col2 = r.normal(loc=7,scale=2,size=1000)
col3 = r.logistic(loc=11,scale=3,size=1000)
col4 = r.exponential(scale=4,size=1000)
col5 = r.geometric(p=0.7,size=1000)

test_data = np.array([col1,col2,col3,col4,col5])
print(test_data)
# doesn't look right... transpose
test_data = np.array([col1,col2,col3,col4,col5]).transpose()
print(test_data)
# better!

[[ 1.59077303  2.28243293  1.81098674 ...  0.1973629  -2.21015722
   2.91161235]
 [ 6.42174295  8.57902322  5.17270135 ...  4.3465854   8.2176402
   7.90337695]
 [10.14698427 15.93309953 -0.46878789 ...  2.66485989 12.69328115
  11.79840961]
 [ 6.91500737  6.243605    2.44997251 ...  0.80935387  0.50644607
   4.86816939]
 [ 1.          1.          1.         ...  1.          2.
   1.        ]]
[[ 1.59077303  6.42174295 10.14698427  6.91500737  1.        ]
 [ 2.28243293  8.57902322 15.93309953  6.243605    1.        ]
 [ 1.81098674  5.17270135 -0.46878789  2.44997251  1.        ]
 ...
 [ 0.1973629   4.3465854   2.66485989  0.80935387  1.        ]
 [-2.21015722  8.2176402  12.69328115  0.50644607  2.        ]
 [ 2.91161235  7.90337695 11.79840961  4.86816939  1.        ]]


In [38]:
# save it
np.savetxt('test_data.csv', test_data, fmt='%s', delimiter=',')

In [40]:
a_test = np.genfromtxt('test_data.csv', delimiter=',')
print(a_test)

[[ 1.59077303  6.42174295 10.14698427  6.91500737  1.        ]
 [ 2.28243293  8.57902322 15.93309953  6.243605    1.        ]
 [ 1.81098674  5.17270135 -0.46878789  2.44997251  1.        ]
 ...
 [ 0.1973629   4.3465854   2.66485989  0.80935387  1.        ]
 [-2.21015722  8.2176402  12.69328115  0.50644607  2.        ]
 [ 2.91161235  7.90337695 11.79840961  4.86816939  1.        ]]
