In [1]:
import numpy as np

In [2]:
# ndarray = "n-dimensional array"
# store values in sequence
# operations are elementwise
# e.g. [1,2,3] + [4,5,6] = [5,7,9]

# industry standard for computational operations

In [3]:
a = np.array([1,2,3])
print(a)
print(type(a))

[1 2 3]
<class 'numpy.ndarray'>


In [4]:
# vecotr
# shape = size, dimension 
# Y x X table
# 3col x 1row table
# 1D  = line
print(a.shape)

# short vector
d = np.array([15])
print(d)
# print(type(d))
print(c.shape)

(3,)


In [6]:
# matrix
# "array of arrays" = 2D array
# 2D = plane
b = np.array([[7,8,9], [10,11,12]])
print(b)
# 2row x 3col table
print(b.shape)

print('----------')
# get size (rows)
print(b.shape[0])
# get dimension (cols)
print(b.shape[1])

[[ 7  8  9]
 [10 11 12]]
(2, 3)


In [10]:
# scalar
# point
c = np.array(13)
print(c)
# print(type(c))
print(c.shape)

13
<class 'numpy.ndarray'>
()


In [13]:
# arrays vs lists

# list
l = [n for n in range(6)]
print(l)
print(len(l))

# list within list
i = [[n for n in range(3)], [n for n in range(3)]]
print(i)
# two lists within the list
print(len(i))

# list have length

[0, 1, 2, 3, 4, 5]
6
[[0, 1, 2], [0, 1, 2]]
2


In [16]:
# array = table
a = np.array(l)
print(a)
print(len(a))

# arrays have shape
print(a.shape)
a = np.array([[0,1,2], [3,4,5]])

[0 1 2 3 4 5]
6
(6,)


In [17]:
# adding lists just sticks them together
list_add = l + i
print(list_add)

# adding arrays computes elementwise operation
array_add = a[0] + a[1]
print(array_add)

[0, 1, 2, 3, 4, 5, [0, 1, 2], [0, 1, 2]]
[3 5 7]


In [19]:
import math
# can't do math on the lists
# print(math.sqrt(l))

# CAN on arrays
print(np.sqrt(a))

[[0.         1.         1.41421356]
 [1.73205081 2.         2.23606798]]
