In [1]:
import numpy as np

In [5]:
from random import randint
m = np.array([[randint(0,10), randint(0,10), randint(0,10)], [randint(0,10), randint(0,10), randint(0,10)]])
print(m)

[[3 9 1]
 [5 0 2]]


In [17]:
# slicing
# "closed-open" = starts on the first number, but doesn't include the stop number
# default rows
# all rows
print(m[:])
print('--------------------')
# row n
print(m[1])
print('--------------------')
# all rows, n column
print(m[:,2])
print('--------------------')
# all cols, 0 row
print(m[0,:])
print('--------------------')
# rows beginning to 1, all cols
print(m[:2, :])
print('--------------------')
# all rows, cols 2 to the end
print(m[:, 2:])

[[3 9 1]
 [5 0 2]]
--------------------
[5 0 2]
--------------------
[1 2]
--------------------
[3 9 1]
--------------------
[[3 9 1]
 [5 0 2]]
--------------------
[[1]
 [2]]


In [18]:
# stepwise slicing
# 3 x 5 matrix
mb = np.array([[randint(0,10),randint(0,10),randint(0,10),randint(0,10),randint(0,10)],
               [randint(0,10),randint(0,10),randint(0,10),randint(0,10),randint(0,10)],
               [randint(0,10),randint(0,10),randint(0,10),randint(0,10),randint(0,10)]])
print(mb)

[[ 9  5  4  0  6]
 [10  2  3  7  2]
 [10  6  4  5  8]]


In [29]:
# start-stop-step
# default step = 1
# all rows, all cols, step 2 in dimension 1
print(mb[::2, ::])
print('--------------------')
# every 2 values from every 2 rows
print(mb[::2, ::2])
print('--------------------')
# negative step - move through backwards
# start from last and move backwards
print(mb[-1::-1, -1::-1])

[[ 9  5  4  0  6]
 [10  6  4  5  8]]
--------------------
[[ 9  4  6]
 [10  4  8]]
--------------------
[[ 8  5  4  6 10]
 [ 2  7  3  2 10]
 [ 6  0  4  5  9]]


In [36]:
# conditional slicing
# 3 x 5 matrix
mc = np.array([[randint(0,10),randint(0,10),randint(0,10),randint(0,10),randint(0,10)],
               [randint(0,10),randint(0,10),randint(0,10),randint(0,10),randint(0,10)],
               [randint(0,10),randint(0,10),randint(0,10),randint(0,10),randint(0,10)]])
print(mc)

[[ 2 10  2  3  1]
 [ 0  4  7  7  6]
 [10  0  7  1  2]]


In [40]:
# all rowss, col0
print(mc[:,0])
print('--------------------')
# bool
print(mc[:,0] > 2)
print('--------------------')
# index the bool
# apply to flattened array = all rows stacked int he same order
print(mc[mc[:,:] > 2])
print('--------------------')
# all even numbers <= 4 or == 10
print(mc[(mc[:,:] % 2 == 0) & (mc[:,:] <= 4) | (mc[:,:] == 10)])

[ 2  0 10]
--------------------
[False False  True]
--------------------
[10  3  4  7  7  6 10  7]
--------------------
[ 2 10  2  0  4 10  0  2]


In [41]:
# squeeze
md = np.array([[randint(0,10),randint(0,10),randint(0,10),randint(0,10),randint(0,10)],
               [randint(0,10),randint(0,10),randint(0,10),randint(0,10),randint(0,10)],
               [randint(0,10),randint(0,10),randint(0,10),randint(0,10),randint(0,10)]])
print(md)

[[ 9  6  5  8 10]
 [ 7  1  3  4  6]
 [ 2  7  9  9  2]]


In [46]:
# type of the first element
# int
print(type(md[0,0]))
# scalar
print(md[0,0])
# type of first row, cols beginning to first (first col)
# array
print(type(md[0, 0:1]))
# scalar in vector
print(md[0, 0:1])
# vector in vector
print(md[0:1,0:1])

<class 'numpy.int32'>
9
<class 'numpy.ndarray'>
[9]
[[9]]


In [51]:
# squeeze
# take the vector of vectors...
print(type(md[0:1,0:1]))
print(md[0:1,0:1])
# ... and squeeze
# returns a 0D array
print(type(md[0:1,0:1].squeeze()))
print(md[0:1,0:1].squeeze().shape)
print(md[0:1,0:1].squeeze())

<class 'numpy.ndarray'>
[[9]]
<class 'numpy.ndarray'>
()
9
